// Pure conversions between Task Sloth rows and Google Tasks resources.

/** Everything after this marker in Google's notes is generated by us and ignored when reading back. */
export const NOTES_MARKER = "\n\n— via Task Sloth —";

export function taskToGoogle(task, { appUrl }) {
  const footer = [task.project_name && `Project: ${task.project_emoji ?? ""} ${task.project_name}`.replace(/\s+/g, " "),
    task.due_time && `Time: ${task.due_time}`,
    task.context_name && `Context: ${task.context_name}`,
    task.tag_names && `Tags: ${task.tag_names.split(" ").sort().map((t) => `+${t}`).join(" ")}`,
    task.item_count > 0 && `Checklist: ${task.item_done}/${task.item_count}`,
    `Open: ${appUrl}/tasks/${task.id}`]
    .filter(Boolean)
    .join("\n");
  const done = task.status === "done";
  return {
    title: task.title,
    notes: `${task.notes ?? ""}${NOTES_MARKER}\n${footer}`.trimStart(),
    // Google Tasks stores a date only; the time portion is discarded by the API.
    due: task.due_date ? `${task.due_date}T00:00:00.000Z` : null,
    status: done ? "completed" : "needsAction",
    completed: done ? (task.completed_at ?? new Date().toISOString()) : null,
  };
}

export function itemToGoogle(item) {
  return {
    title: item.quantity ? `${item.text} (${item.quantity})` : item.text,
    status: item.checked ? "completed" : "needsAction",
    completed: item.checked ? item.updated_at : null,
  };
}

export function stripNotes(notes) {
  const s = notes ?? "";
  const i = s.indexOf(NOTES_MARKER.trim());
  return (i === -1 ? s : s.slice(0, i)).trimEnd();
}

/** Fields of an app task as described by a Google task. */
export function googleToTaskFields(g) {
  return {
    title: (g.title ?? "").trim() || "(untitled)",
    notes: stripNotes(g.notes),
    dueDate: g.due ? g.due.slice(0, 10) : null,
    done: g.status === "completed",
  };
}

export function googleToItemFields(g) {
  const title = (g.title ?? "").trim();
  const m = title.match(/^(.*\S)\s+\(([^()]+)\)$/);
  return {
    text: (m ? m[1] : title) || "(untitled)",
    quantity: m ? m[2] : null,
    checked: g.status === "completed",
  };
}

/**
 * Decides whether a change seen in Google should overwrite the app's copy.
 * Last write wins: if both sides changed since the last sync, the newer timestamp wins.
 */
export function shouldApplyRemote({ remoteUpdated, localUpdated, lastSynced }) {
  const localChanged = localUpdated > lastSynced;
  if (!localChanged) return true;
  return new Date(remoteUpdated).getTime() > new Date(localUpdated).getTime();
}
